### PR TITLE
feat: use chrome custom tabs for links

### PR DESCRIPTION
**Pull request by beatbrot**
Use chrome custom tabs on Android for links.

This allows users to share the link of a recipe and also arguably gives a better browser experience on Android.

### CODE REVIEW

**Review by TomBursch — COMMENTED** [review]
This feature looks great! But what happens on Linux/Mac/Windows? Should we keep the url_launcher behavior for those platforms?

**Comment by TomBursch** [comment]
Also that package seems a bit poorly maintained, what do you think about [this](https://pub.dev/packages/flutter_inappwebview) package as a replacement? It also has custom tabs support https://inappwebview.dev/docs/5.x.x/in-app-browsers/chrome-safari-browser/

**Comment by beatbrot** [comment]
> This feature looks great! But what happens on Linux/Mac/Windows? Should we keep the url_launcher behavior for those platforms?

You are right. This is broken on linux. I'll give this another try :) I'll ping you, when I am done :)

**Comment by beatbrot** [comment]
@TomBursch I am not really convinced of the library you linked. It makes the APK 20MB larger compared to the current solution and doesn't support animations when opening/closing custom tabs. Not even the default ones. Also, the documentation references classes that don't really exist.

What should we do in your opinion? Just falling back to urllauncher on web/win/linux/macos? Searching for yet another library?

**Review by TomBursch — APPROVED** [review]

**Pull request merged**
