### PR TITLE
feat: Categorize recent items #149

### PR DESCRIPTION
**Pull request by rmax1024**
Add categories for recent items, make recent category titles smaller and italic to visually separate them from original categories.

### CODE REVIEW

**Comment by TomBursch** [comment]
Why did you close this? 😄 I just didn't have time to look at it yet, but probably would have merged this today

**Comment by rmax1024** [comment]
Oh, OK. I just took a look to your another PR with infinite recent items, which would contradict mine and thought you would not approve my changes. Reopen now for your review.

**Review by TomBursch — APPROVED** [review]
LGTM

**Comment by TomBursch** [comment]
Thanks! That PR was more or less just a test and worked not that great, I think this is a better solution.

**Pull request merged**
