### PR TITLE
Experiment: Integrate backend into main repo

### PR DESCRIPTION
**Pull request by beatbrot**

### CODE REVIEW

**Comment by beatbrot** [comment]
@TomBursch Based on the discussion in #346, I tried to rewrite the history of the backend repo so that all files are in a "backend" folder for every commit of the whole history. 
This breaks all GPG signatures of all commits. Also the issues and PRs referenced in commit messages are now pointing to the wrong location.
In addition to that, it doesn't make sense that there is a `backend/.github` folder. This folder should've been excluded from the relocation.
I believe these issues are fixable.

Of course, it does not make sense to merge this as-is and in the end, it is of course your decision whether you want to merge the repos or not. I just wanted to do some experimentation and share my findings with you :)

**Comment by TomBursch** [comment]
Wow, looks good, I'm fine without the signatures as long as all code ownership is still available (which it seems like it is). 

> Both variants would take me some weeks though.

I guess they didn't 😄

**Comment by beatbrot** [comment]
@TomBursch One follow-up question: What should we do with all the tags that were in the backend repo? Delete them? Give them a "backend-" prefix?

**Comment by TomBursch** [comment]
We can delete them. I've done some smaller fixes and published a new release, so I'll focus on this next.

**Pull request closed without merging**
